### ISSUE TITLE
date-picker: `setFocus( )` method not focusing first focusable element

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#10243]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When `setFocus( )` is invoked on `calcite-date-picker` , focus is not visible.

### Expected Behavior

Should focus first focusable element in `calcite-date-picker`.

### Reproduction Sample

https://codepen.io/anvesh-mekala/pen/jOjXKWp

### Reproduction Steps

1. Open Codepen
2. Click on `setFocus` button
3. Observe no element in date-picker receives focus.

### Reproduction Version

2.12.1

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by driskull** [comment]
`focusFirstTabbable(this.el);` doesn't find any focusable elements because all the focusable elements are within another shadowDOM. The component will probably need to add a setFocus method to the date picker month header. I think the header should always be there and have a focusable element.

**Comment by DitwanP** [comment]
🍡 Verified on `2.14.0-next.18` 

https://codepen.io/Ditwan-Price/pen/poMLKGJ?editors=1010
