### ISSUE TITLE
date-picker: `maxAsDate`& `minAsDate` are ignored.

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#10329]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

`calcite-date-picker` ignores `maxAsDate` and `minAsDate` properties. Adding them has no effect.

### Expected Behavior

- Dates before `minAsDate` should be disabled.
- Dates after `maxAsDate` should be disabled.

### Reproduction Sample

https://codepen.io/anvesh-mekala/pen/RwzzryJ?editors=1010

### Reproduction Steps

1. Open CodePen
3. Observe dates before `minAsDate` &  after`maxAsDate` are not disabled.

### Reproduction Version

2.12.2

### Priority impact

impact - p2 - want for an upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by paulcpederson** [comment]
Adding the ArcGIS Online label as this is impacting our product as well.
