### ISSUE TITLE
Epic: Provide consistent dragging experiences and support across components

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#10383]
**monday.com sync:** #18048509134

### Description
Provide a consistent dragging experience across components using `dragEnabled` so users can have consistent and expected experiences.

### Components/Efforts
- [ ] https://github.com/Esri/calcite-design-system/issues/10381
- [x] `block` https://github.com/Esri/calcite-design-system/issues/10382
- [ ] `chip-group` https://github.com/Esri/calcite-design-system/issues/6643
- [ ] `tabs` https://github.com/Esri/calcite-design-system/issues/6639
