### ISSUE TITLE
[Action-named components] Update action design for 5.0

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#10759]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Improve UI/UX for `action-`based components to support more use cases across the design system.

Blocked issues: #7052, #11802, #10777
Blocked by: #11906 

### Acceptance Criteria

See this [Figma file](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1889-6223&m=dev) for the following:
1. **`action` component**:
    - [x] Adjust internal `padding` to reduce height at each scale
        - [ ] small: 24px
        - [x] medium: 32px
        - [ ] large: 44px
    - [x] Update `gap` between icon and text
    - [x] Round corners to 2px
    - [x] Update `appearance` default to `"transparent"`
    ~~- [x] Deprecate `appearance="solid"` in favor of `transparent`~~
    - [x] add `selectionAppearance` prop via #10758
2. **`action-group` component**
    - [x] Add `gap`
    - [x] Add `padding` to trailing divider to align to border-radius of Actions
    - [ ] add `selectionMode` prop via #7052
3. **`action-bar` + `action-pad` components**
    - [x] Add `padding` and `gap`, maintaining current bar/pad dimensions
    - [x] add `selectionAppearance` prop via #10758 
4. **`action-menu`**
    - [x] Add `padding` and `gap`, maintaining current bar/pad dimensions

Before/after at medium scale pictured below. See [Figma file](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1889-6223&m=dev&focus-id=1919-4001) for full specs.

![Image](https://github.com/user-attachments/assets/a531b605-6b70-4da3-ad4b-c3f4699d0f9e)

### Relevant Info

Part of 4.0's Phase I - Actions

~~Blocked Issues: #6640, #10781~~

### Which Component

- `action`
- `action-group`
- `action-bar`
- `action-pad`

### Example Use Case

Refer to relevant info above.

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**monday.com sync:** #9367077560

**Comment by DintaMel** [comment]
@ashetland with the change to deprecate `solid` in favor of `transparent`, will users not be able to have a submit action background color in the future? 

Example: In the `Action Bar` sample "Action Bar with Contextually Displayed Action Bars", there is a green submit button. With the changes to be transparent, applying background color will no longer work. [Codepen](https://codepen.io/DintaMel-the-lessful/pen/GgZPOGe?editors=1000)

Before:
<img width="577" height="102" alt="Image" src="https://github.com/user-attachments/assets/f087d8de-2f3f-48a7-b712-11217feb4309" />


After:
<img width="549" height="89" alt="Image" src="https://github.com/user-attachments/assets/82aec15c-fe23-4c64-9a12-9f3821bdc7a9" />

**Comment by eriklharper** [comment]
> [@ashetland](https://github.com/ashetland) with the change to deprecate `solid` in favor of `transparent`, will users not be able to have a submit action background color in the future?

Good question.  Rather than deprecate `solid` we could just document that the default is now transparent and keep solid around for this.

**Comment by ashetland** [comment]
Yeah we weren't 100% sure about the fallout of this. Why do the css props for theming not work on `transparent`?

**Comment by ashetland** [comment]
I'm fine keeping `solid` around and changing the default, but I expected `--calcite-action-background-color` to also map to the `transparent` appearance.

**Comment by DintaMel** [comment]
Setting  appearance to `transparent` essentially makes the background/foreground props invisible. They're still being applied, you just can't see them on the screen.

Here's an example of what the button above would look like with the new changes and a solid appearance. 

<img width="517" height="71" alt="Image" src="https://github.com/user-attachments/assets/3be3b514-511e-4074-87e3-9d7fb66be611" />

**Comment by ashetland** [comment]
Ahhh, okay then. Sounds like we'll need to just change the default, but keep `solid` around. Not sure why we didn't catch this before 🤦‍♂️.

**Comment by DintaMel** [comment]
It's easy to miss. 

@eriklharper I'm putting this back in `3 - in development` to make the change to no longer deprecate `solid`.  

@geospatialem tagging you as an fyi if this impacts your migration plan for the action design changes.

**Comment by eriklharper** [comment]
Great catch on this Mel!  Appreciate your input :)

**Comment by DintaMel** [comment]
Verified using 5.0.0-next.21 on [codepen](https://codepen.io/DintaMel-the-lessful/pen/ByKMovg?editors=1000)

**Comment by ellenupp** [comment]
Hi @DintaMel, @eriklharper, @ashetland 
I wanted to confirm whether or not the `appearance` prop is being deprecated? There is still a deprecation notice in the component/doc but from the above discussion it sounds like it will not be. 

BTW theming a transparent action does work using component tokens, ex `--calcite-action-background-color`, rather than with semantic tokens as in the above example.

**Comment by DintaMel** [comment]
> I wanted to confirm whether or not the `appearance` prop is being deprecated?

@ellenupp We did decide to deprecate the `appearance` property in favor of using tokens since the `appearance` property and tokens were sometimes conflicting. See the [thread in issue #13462 ](https://github.com/Esri/calcite-design-system/issues/13462#issuecomment-3676420653) for more context.
