### ISSUE TITLE
Update components to account for new v5.0 `calcite-action` design

### ISSUE THREAD

**Issue by DitwanP** [Esri/calcite-design-system#10777]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

Blocked issues: https://github.com/Esri/calcite-design-system/issues/12364

### Description

The changes to Actions from issue #10759 necessitate updates to any components that use Actions. Outlined below on a per-component basis:
- Updated Actions spacing
- Updated action-slot spacing
- Updated close buttons
- Actions should no longer stretch to fill the height of their container

[See Figma file for full details 🔗](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions--Action-Bar--Action-Group-updates?node-id=1781-16462)

Overview example using a representative set of components showing updated spacing and improved alignment:
![Image](https://github.com/user-attachments/assets/12d41a4e-6459-49e0-bb71-7521be9900de)

### Acceptance Criteria

- [x] **Accordion Item**: update action slot spacing ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=1927-8814)) #13416

- [x] **Alert**: update actions-end slot spacing and use `calcite-action` for close button ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3503-14883)) #13417 

- [x] **Block**: update action slots and sort-handle spacing ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3505-20088)) #13429 

- [x] **Chip**: use `calcite-action` for close button ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3601-20709)) @eriklharper #13445

- [x] **Dialog / Flow Item / Panel**: update spacing of action-slots, close, collapse, and menu buttons ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3532-116263)) https://github.com/Esri/calcite-design-system/pull/13437

- [x] **Flow / Flow Item**: remove border from back button ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3532-155869)). **Note:** dependent upon action slot updates from Panel https://github.com/Esri/calcite-design-system/pull/13449

- [x] **List**: update filter actions slot spacing ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3553-32901)) @Amretasre002762670 #13463 

- [x] **List Item**: update sort-handle, actions slots, and close button spacing ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3553-32901)) @Amretasre002762670 #13463 

- [x] **Menu Item**: update submenu-item action spacing and border ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions--Action-Bar--Action-Group-updates?node-id=1781-16462&m=dev&focus-id=5068-20327)) (https://github.com/Esri/calcite-design-system/pull/13440)

- [x] **Navigation**: update navigation-action spacing ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3557-40215)) (https://github.com/Esri/calcite-design-system/pull/13434)

- [x] **Notice**: update actions-end slot spacing and use `calcite-action` for close button ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3557-53360)) (https://github.com/Esri/calcite-design-system/pull/13432)

- [x] **Popover**: use `calcite-action` for close button ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3657-147720)) https://github.com/Esri/calcite-design-system/pull/13433

- [x] **Tab Title**: use `calcite-action` for close button ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3684-136181)) https://github.com/Esri/calcite-design-system/pull/13444

- [x] **Table**: add gap to selection-actions ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3557-76702)) https://github.com/Esri/calcite-design-system/pull/13436

~- [ ] **Tip / Tip Manager**: update close button spacing ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3701-147898))~ **removed at 5.0**

- [x] **Tree Item**: add gap to actions-end slot ([See full Figma spec for details](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3628-61924)) https://github.com/Esri/calcite-design-system/pull/13435

### Relevant Info

Part of 5.0's Phase 2

Blocked by: #10759

### Which Component

Accordion Item, Alert, Block, Chip, Dialog, Flow, Flow Item, List, List Item, Menu, Navigation, Notice, Popover, Tab Title, Table, Tip, Tip Manager, Tree Item

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

Calcite (design)

**monday.com sync:** #9367125441

**Comment by isaacbraun** [comment]
Awesome work all, these changes are looking amazing!! 🤩 Only a couple issues found during verification. Refer to the CodePen below if needed.

https://codepen.io/isaacbraun/pen/WbxQjbj

- [x] `Flow Item`: "back" `Action` does not inherit the scale from `Flow` as required.
- [x] `List Item` drag handles - should double-check [the Design Spec](https://www.figma.com/design/i6iep7fCM0yAHscPm6i7aG/Actions%2C-Action-Bar%2C-Action-Group-updates?node-id=1781-16462&m=dev&focus-id=3553-32901) in addition to my findings.
	1. On `scale="s"`, `actions-start` has extra padding added. I believe it can be removed on [LN#206](https://github.com/Esri/calcite-design-system/blob/e28681d98fe91b15f5e5e373e95bbc4499531080/packages/components/src/components/list-item/list-item.scss#L206-L208).
	2. All Modes/All Scales: Wherever `.drag-container` has `margin-inline` set, it should be `var(calcite-spacing-xxs)` instead of `var(--calcite-internal-list-action-spacing)`. The internal var works fine for `s/m` scales but not for `l`.
		1. For `selection-appearance=“icon” selection-mode=“multiple | single”` and `display-mode="nested"`, the only margin should be on `margin-inline-start`.
	4. There is extra padding applied to the default `flat` mode drag handles via the below rules (and maybe more). This should not be applied.
		```css
		:host([display-mode="flat"][drag-handle]:is([selection-mode="none"], [selection-appearance="highlight"])) .drag-container {
  			padding-inline-end: var(--calcite-spacing-xxs);
		}
		:host([display-mode="flat"][drag-handle]:is([selection-mode="none"], [selection-appearance="border"])) .drag-container {
  			padding-inline-end: var(--calcite-spacing-xxs);
		}
		```
	6. The below rule is missing for `scale="l"`. With the other padding issues, these rules should probably be rethought.
		1. `:host([scale=m][display-mode=flat][drag-handle][selection-appearance=icon]:is([selection-mode=multiple], [selection-mode=single])) .drag-container`

**Comment by isaacbraun** [comment]
Verified on `5.0.0-next.53` using the Design Spec for acceptable criteria via https://codepen.io/isaacbraun/pen/WbxQjbj. Great job everyone! 🎉
