### ISSUE TITLE
Enhancement: add month-year and year appearance to calcite date picker

### ISSUE THREAD

**Issue by fendiaoxiaoshuazi** [Esri/calcite-design-system#3455]
### Description
Support month-year and year only appearance in the calcite date picker.

Here are the screenshots of the month-year and year only appearance in bootstrap date picker
![image](https://user-images.githubusercontent.com/26078106/140918561-ee99475e-689a-474f-9780-3346542b5645.png)
![image](https://user-images.githubusercontent.com/26078106/140918589-baeb0b95-a078-479b-a2c0-5925a3130f0d.png)

### Relevant Info 
Blocked issues: #9167, #8624, #10291, #10243, #10490

#### Which Component
`calcite-date-picker`

**Comment by fendiaoxiaoshuazi** [comment]
Hi calcite team, I am a PE of the Survey123 team, and we are currently working on replacing our date and time picker with the calcite date and time picker for better A11y and I18N support. The month/year and year only appearance is critical for us, so we cannot fulfill the replacement at this point.

Do you have a timeframe time for this enhancement to be implemented?

**Comment by fendiaoxiaoshuazi** [comment]
Hi Calcite team, we have partially replaced our pervious Wijimo date/time picker with the Calcite date/time picker. Since Calcite does not support month year and year only appearances, we have to keep the Wijimo date picker to support these appearances. 

Therefore, we need to load 2 different libs for the date/time question, and there are many month year and year only appearances I18N issues are impeded by the replacement work. 

We are waiting for Calcite to support month year and year only appearances to proceed with the replacement work.

**Comment by fendiaoxiaoshuazi** [comment]
Hi Calcite team, we need to upgrade node.js to the latest version as required by the Security team, and we probably have to drop the Wijimo lib which we currently use for month-year and year-only appearances. 

Therefore, Calcite's month-year and year-only appearances support become the pre-requisite of our node upgrade. We plan to upgrade node.js and drop Wijimo in our UC Release. If possible could you please prioritize this issue, and address this issue before May?

**Comment by benelan** [comment]
Hi @fendiaoxiaoshuazi, sorry for the delay! I'll make sure to bring it up again during our next triage. It is definitely a valid use case and something we would like to implement. However it is unlikely to be done by May, since it would require design and i18n feedback before development can start.

Which Node version are you currently on? If you're on an Active or Maintenance LTS version, updating to the latest minor/patch version should be sufficient security-wise. That should give us more time until your current date components need to be replaced.

https://nodejs.org/en/blog/vulnerability/february-2023-security-releases/

We are also revamping some of our processes so we can better communicate our plans and progress. Our original triage was scaled down during the lead up to v1, but we are starting to work through the back-fill. Thanks for the patience everyone!

**Comment by yixi8524** [comment]
@benelan Thanks for your prompt reply. We are still in Node.js 14 & NPM6 env. We must plan the next release to upgrade our Env and libs. Not only Node.js also include NPM, Webpack, Angular Framework, etc. So this is a good time to refactor our lib. If we can retire the Wijimo ASAP, it can let us easy to control the i18n and the A11Y support. Give the same and better UX experience to our users.

**Comment by SkyeSeitz** [comment]
Howdy folks! Can I get some eyes on [this proposed design ](https://www.figma.com/file/eP9IJjZV95HVKRCbNmW6eX/Input-Date-Picker-%5B%233455%5D?type=design&node-id=404%3A164648&t=8eS2Mi61b3WiUnoP-1)? Looking for feedback before moving any further. Thanks!
@macandcheese @jcfranco 
<img width="1674" alt="image" src="https://github.com/Esri/calcite-components/assets/29716057/ebd99fc4-e383-43a2-92cd-6c23ef7703a4">

**Comment by SkyeSeitz** [comment]
Updated and expanded the scope of the proposed design based on design and engineering feedback from the team. Updated specs can be found [here](https://www.figma.com/file/eP9IJjZV95HVKRCbNmW6eX/Input-Date-Picker-%5B%233455%5D?type=design&node-id=509-98979).

**Comment by SkyeSeitz** [comment]
Updated specs in Figma after some hot potato: https://www.figma.com/file/eP9IJjZV95HVKRCbNmW6eX/Date-Picker-Redesign-%5B3455%5D?type=design&node-id=898%3A41827&mode=design&t=FWbpCQwwI4Ey9k7C-1

**Comment by geospatialem** [comment]
Could the redesign of the component also account for https://github.com/Esri/calcite-design-system/issues/6410, where when the component is in `scale` of `"l"`.  cc @anveshmekala

**Comment by anveshmekala** [comment]
> Could the redesign of the component also account for #6410, where when the component is in `scale` of `"l"`. cc @anveshmekala

yeah, the redesign will resolve that issue, user's can select years rather than typing them.

**Comment by anveshmekala** [comment]
Attaching [wiki notes](https://github.com/Esri/calcite-design-system/wiki/date%E2%80%90picker-enhancement-%238402) for reference. 

cc @jcfranco @geospatialem

**Comment by DitwanP** [comment]
The original ask of this issue has been broken off into these new issues:
https://github.com/Esri/calcite-design-system/issues/9394
https://github.com/Esri/calcite-design-system/issues/9393

And this issue was repurposed to add the following enhancements to `date-picker`:

### Changes
- [x] display two calendars for range irrespective of layout.
- [x] No longer switches focus from day to end input when startDate is selected initially.
- [x] Month selection is possible via select menu
- [x] No longer positions the date-picker component relative to endInput when endInput is focused in range.
- [x] Dates from previous months are not visible in range calendar.
- [x] Divider indicator icons are removed in horizontal layout for range in input-date-picker.
- [x] No longer uses chevron icon which indicate the open status of input-date-picker in startInput field.

🍡 Verified locally on `dev`
