### ISSUE TITLE
Consistent focus/blur eventing across components

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#5147]
**monday.com sync:** #18048591137

### Overview

Currently, developers have to rely on `focusin`/`focusout` (composable + bubbling) from component internals or using, internal, blur/focus events for a few components.† 
The goal for this effort is to provide a general solution for focus/blur events given that these events are commonly used and expected in many web development scenarios.

Also for consideration, `setFocus` has introduced a pattern that can lead to inconsistent focus behavior. Existing usage should be revisited to see if we can consolidate in favor of consistency (one focus pattern to rule them all).   

† In general, this works but leads to boilerplate code as `focusin`/`focusout` fires when you move between elements inside a component and would need to check where focus lies when handling the event.

### Tasks

- [ ] determine if `delegatesFocus` is a viable solution
  - [x] consult design regarding potential double focus outline 
      - **Design suggests hidding the focus ring on the host and only displaying it on the element it delegates focus to. a11y agrees with the recommendation**
      - ** Note I haven't seen any double focus rings yet, it may have been a quirk that is worked out now**

  - [x] check browsers focusing is consistent, if not weigh options
      - **As usual, browsers behave differently when it comes to focus  ([example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus)).  However, since `delegatesFocus` is a web standard, I think we will have better consistency than we would if we try to jerry-rig up our own solution. Once we get it set up in the code we can do more browser testing, but all the browsers have adopted the pattern and are reletaively consistent, based on my research.***

  - [ ] check that focus/blur events will behave as expected for both light/shadow DOM content (if so, we use these and drop our internal focus/blur events)
  - [ ] confirm dev expectations light/shadow DOM content focus/blur (e.g., blurring slotted content not emitting blur on custom element) - https://codepen.io/jcfranco/pen/ZExMgwx?editors=1000
  - [x] check if https://www.npmjs.com/package/delegates-focus-polyfill will fit the bill since Safari 14 doesn't support it
      - **Safari 16 released so we don't need the polyfill**

- [ ] consult design, a11y concerns from having multiple focus targets from `setFocus`
  - if keeping single focusable target, we should consider promoting `calciteComponent.focus/blur()` for shadow-targeted focus/blur or `slottedContent.focus/blur()` for light-targeted focus/blur

### Additional resources

- https://github.com/whatwg/html/issues/7207
- https://github.com/WICG/webcomponents/issues/830#issuecomment-525816320
- https://github.com/Esri/calcite-components/issues/5132
- https://github.com/Esri/calcite-components/issues/3626

cc @benelan @geospatialem

**Comment by benelan** [comment]
## Findings

It turns out `delegatesFocus` does not take into account `tabindex` or `pointer-events: none` when determining the first focusable element on `click` and `focus()`. This is an issue for us because components emulated as `disabled` will still be delegated focus if they are the first element in the flat tree. 

Using [`inert`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert) on the mock "disabled" element solves this issue, but there isn't enough [browser support](https://caniuse.com/mdn-api_htmlelement_inert) at the moment.

## Next steps

I will continue enabling `delegatesFocus` for the components that don't have the possibility of the first focusuble element being mock "disabled". I will add a list of the components being skipped at the bottom of this comment so we can circle back later.

## Resources

Here is a codepen demonstration: https://codepen.io/benesri/pen/PoavMWM


Here is the WICG issue where they made that decision: https://github.com/WICG/webcomponents/issues/830

Specifically this snippet from the issue body:

> Since we want to change the behavior of focus delegation to not be related to sequential focus navigation, we should probably remove the tabindex priority thing as well in this case. So we should always delegate focus to the first focusable area in DOM/composed-tree order

and this comment near the bottom:

> Sounds like there was a consensus to move forward with what's being proposed thus far:
> - Programmatic focus would focus the first element in the flat tree that's programmatically focusable.
> - Mouse focus would focus the first element in the flat tree that's mouse focusable.
> - Keyboard focus would focus the first element in tab index order that's keyboard focusable.


## Skipped components
- `calcite-list*` components (the first list item can be mock disabled)

**Comment by benelan** [comment]
@geospatialem I moved this to Stalled because a lot of the components need Franco's feedback. But can you please verify the components that have been completed so far when you have time? You can use the `setFocus` method to ensure the first focusable element is focused. Here is an example for `filter`:
https://codepen.io/benesri/pen/XWYvoGa?editors=1010

- [ ] `dropdown`
- [ ] `dropdown-group`
- [ ] `action-bar`
- [ ] `action-group`
- [ ] `action-pad`
- [ ] `date-picker`
- [x] `filter`
- [ ] `inline-editable`
- [ ] `input-date-picker`
- [ ] `input-time-picker`
- [ ] `time-picker`
- [ ] `split-button`
- [ ] `pagination`
- [ ] `radio-button-group`
- [ ] `slider`

**Comment by geospatialem** [comment]
@benelan Thanks for the thorough list to work through! I wasn't able to verify the `setFocus` method for the components listed below. 

Is there an additional step needed to ensure `setFocus` is selecting the first focusable element?

- `dropdown`: https://codepen.io/geospatialem/pen/QWBLEPz
- `action-group`:https://codepen.io/geospatialem/pen/ZEjzOgz
- `date-picker`: https://codepen.io/geospatialem/pen/jOpNMOR
- `inline-editable`: https://codepen.io/geospatialem/pen/QWBLKwo
- `split-button`: https://codepen.io/geospatialem/pen/abjomOZ or
- `pagination`:  https://codepen.io/geospatialem/pen/qByWaOr

**Comment by benelan** [comment]
Taking another look at inline-editable. The rest don't have `setFocus()` methods so you can use a timeout and `focus()`

```js
  customElements
    .whenDefined("calcite-date-picker")
    .then(() => setTimeout(() => document.querySelector("calcite-date-picker").focus(), 1000));
```

**Comment by benelan** [comment]
This works for inline-editable

```js
(async () => {
  await customElements.whenDefined("calcite-inline-editable");
  const el = await document
    .querySelector("calcite-inline-editable")
    .componentOnReady();
  requestAnimationFrame(() => el.setFocus());
})();
```

**Comment by geospatialem** [comment]
Awesome, thanks for the insights! ✨ The above components are verified, will await for discussion on the skipped components upon Franco's return.

**Comment by geospatialem** [comment]
Updated scoping to the above as follow-up is needed, WRT the issue's summary section of `Next Steps` of:
>  Check with @jcfranco about the skipped items when he returns.
