### ISSUE TITLE
Epic: Keyboard a11y with arrow keys, `Home`, and `End` for components

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#5470]
**monday.com sync:** #18048508878

### Background
This epic organizes components we're seeking to enhance keyboard accessibility using the `Home`, `End`, and arrow keys. 

This epic across components will provide a better supported behavior for assistive technology and keyboard users.

As opposed to using the `Tab` and `Shift` + `Tab` keys, which shouldn't be the expected behavior with the components listed below.

Came up as a resolution for components when discussing #5113. 

### Plan of action
Anticipated after the v1.0.0 release

### Components
- [ ] Accordion / Accordion Item
- [ ] Pagination
- [ ] Consider for the new carousel component in #6536

#### Other potential components
_Note: may be solved with the list component refactor._
- [x] List / List Item Group / List Item
- [x] Pick List / Pick List Group / Pick List Item - N/A, deprecated
- [x] Value List / Value List Group / Value List Item - N/A, deprecated

cc @macandcheese for usability feedback considerations

**Comment by geospatialem** [comment]
Spike to confirm applicable components across the design system for consideration.

**Comment by geospatialem** [comment]
Confirmed only `accordion` and `pagination` should support the `home` and `end` keys. The new effort with the `carousel` component may want to consider the keys if it fits the new design.

Adding the `docs` label to the above effort ☝🏻 , as once this effort is completed we should also add to the keyboard accessibility section to the component doc pages.
