### ISSUE TITLE
[date-picker]: rounds up all remaining styling bugs

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#6321]
### Actual Behavior

Rounds up all remaining styling bugs on date-picker:

- [x]  Hover starts selecting from the beginning of the month (https://github.com/Esri/calcite-components/issues/6194)
- [ ]  Unwanted blue gradient highlight when hovering/active/selected on the start-range date
- [ ]  Same behavior when the start-range date is selected and the end-range is being hovered/active/selected
- [ ]  Hovering/active past end-range also creates an unwanted white highlight over the grey gradient
- [ ]  All these issues are true and need to be addressed for both rtl and ltr
<img width="477" alt="1__213818983-9019a308-aaa1-4668-9573-21b1de5411a1" src="https://user-images.githubusercontent.com/3362490/218834211-31418a3c-4401-42ef-8243-d1b0cbfddaa4.png">
<img width="435" alt="2__213818984-ae875dcf-48a2-45fb-a92e-9463783166f8" src="https://user-images.githubusercontent.com/3362490/218834242-8fc80623-4cb3-416e-88f3-d38ac60815e5.png">
<img width="410" alt="3__213818980-5b3eb4ba-efb9-44a8-ad14-fe6c14c14956" src="https://user-images.githubusercontent.com/3362490/218834264-590d5e6f-4beb-4910-96c5-697464bd0ce7.png">

### Expected Behavior
Remove the highlight.

### Reproduction Sample
See demo.

### Reproduction Steps
N/A

### Reproduction Version
v1.0.0-beta.99

### Relevant Info
No response

### Regression?
No response

### Impact
No response

### Esri team
Calcite (dev)

**Comment by geospatialem** [comment]
Need design expertise and input across the date-picker component.

**Comment by SkyeSeitz** [comment]
Remaining listed bugs should be solved by design specs mentioned in this comment on the epic: https://github.com/Esri/calcite-design-system/issues/6721#issuecomment-1593774733

- [ ]  Unwanted blue gradient highlight when hovering/active/selected on the start-range date
- [ ]  Same behavior when the start-range date is selected and the end-range is being hovered/active/selected
- [ ]  Hovering/active past end-range also creates an unwanted white highlight over the grey gradient
- [ ]  All these issues are true and need to be addressed for both rtl and ltr

cc @geospatialem

**Comment by jcfranco** [comment]
@Elijbet Can you confirm the reported styling issues are still present in the latest release? https://github.com/Esri/calcite-design-system/pull/7872 made several changes to `date-picker` and addressed some styling quirks.

**Comment by geospatialem** [comment]
The above has already been covered per https://github.com/Esri/calcite-design-system/issues/6321#issuecomment-1865253926, or will be covered in #3455, targeted for this release in May 2024. Closing the above.
