### ISSUE TITLE
Epic: [List and List Item] Add parity support with Value-List and Pick-List with sorting and removing items

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6430]
### Description

Add full parity to the `list` component, which is provided in the `value-list` and `pick-list` components. cc @jcfranco 

May also include a refactor of the `sortable` utility, which some teams use for their own use and should be consulted if a breaking change is necessary. cc @brittneytewks 

### Acceptance Criteria

- [x] 1. #6554 Drag and drop functionality of the `list-item`s 
   - [x] Mouse and keyboard support
   - [ ] _Keyboard support when screen readers are active for both Windows (NVDA, JAWS) and Mac (VoiceOver) users_ (_see #7426_)
- [x] 2. #6555 Removable functionality of `list-item`s 
   - [ ] Mouse and keyboard support
   - [x] Keyboard support when screen readers are active for both Windows (NVDA, JAWS) and Mac (VoiceOver) users
- [x] 3. #6556 Parent event (on `list`) which emits when changes occur on child `list-item` elements, which include the following props:
    - [x] `selected` (currently supported and available on the [`list item`](https://developers.arcgis.com/calcite-design-system/components/list-item/#api-reference-events-calciteListItemSelect)) cc https://github.com/Esri/calcite-components/issues/6362
    - [x] `dragEnabled`  (_acceptance criteria 1 above_)
    - [x] `remove` (_acceptance criteria 2 above_)
- [x] 4. #6600 
    
### Relevant Info

Once parity is upheld, component removal of `value-list` and `pick-list` should be communicated to stakeholders and customers prior to their removal so developers can migrate their code to the updated `list` component.

Once landed, other issues such as #2489, #3551, #3997, and #6235 should be researched to determine their feasibility for a future milestone/release (if applicable).

### Which Component

- List
- List item

### Example Use Case

Depicted with `value-list` and `value-list-item`: 
https://codepen.io/geospatialem/pen/abjxWwL

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Verified! 🎉
