### ISSUE TITLE
Epic: Ensure components are mobile-web friendly (responsive)

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#6538]
This initiative will focus on making sure components display and work properly in mobile devices.

### Actions

- [ ] define supported breakpoints
- [ ] audit existing component set to scope changes 
- [ ] update components from audit

**Note**: this is a placeholder epic and will be updated with more information

**Comment by geospatialem** [comment]
Closing in favor of https://github.com/Esri/calcite-design-system/issues/6670, which contains more details and the relevant components for the responsive design effort.
