### ISSUE TITLE
[List and List Item] Add List event emits when changes occur on List Items

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6556]
### Description

Add full parity to the `list` component, which is provided in the `value-list` and `pick-list` components. 

### Acceptance Criteria

Parent event (on `list`) which emits when changes occur on child `list-item` elements, which include the following props:
- [x] Event 1: `selected` (currently supported and available on the [`list item`](https://developers.arcgis.com/calcite-design-system/components/list-item/#api-reference-events-calciteListItemSelect)) cc https://github.com/Esri/calcite-components/issues/6362
- [x] Event 2: `dragEnabled`  (from #6554)
- [x] Event 3: `remove` (from #6555)

### Which Component

- List
- List Item

### Example Use Case

Depicted with `value-list` and `value-list-item`: 
https://codepen.io/geospatialem/pen/abjxWwL

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
> @geospatialem need more clarification on this issue.
> 
> The events for closing and selecting already have events which bubble up the DOM. Is the point to listen to these events on the parent list and emit a new event for them?
> 
> Would it be...
> 
> * `calciteListChange` for selected items?
> * `calciteListCloseChange` for closed items?
> 
> I don't think we want one event for both closing and selecting. Drag isn't supported yet so that probably shouldn't be in this issue.
> 
> cc @jcfranco

@driskull Yes, exactly - we received some feedback om [Community](https://community.esri.com/t5/calcite-design-system-questions/list-does-not-have-an-event-for-when-any-of-the/m-p/1260171). Can mark these as seperate asks for tracking. Since the issue is slotted for when drag is scheduled to land, thought this one could be tackled in July to address all three - selected, closed, and moved items on the parent.

**Comment by geospatialem** [comment]
Verified in `main`, with
- List
    -  `calciteListChange`: Emits when `list-item`s selections change.
    - `calciteListOrderChange`: Emits when the order of the component has changed.


- List item
    -  `calciteListItemSelect`: Emits when the item's content is selected.
    - `calciteListItemClose`: Fires when the close button is clicked.
