### ISSUE TITLE
Epic: Tile redesign

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6662]
## Background
Enhance and consolidate functionality of `tile-select` into `tile`.

Once `tile` efforts are completed we'll:
- release the new `tile-group` component and
- deprecate the `tile-select` and `tile-select-group` components

### Phase I
- [x] 1. Keep the following props:
    - [x] `iconFlipRtl` - boolean (`false`)
    - [x] `description` - string (`undefined`)
    - [x] `disabled` - boolean (`false`)
    - [x] `heading` - string (`undefined`)
    - [x] `hidden` - boolean (`false`)
    - [x] `href` - string (`undefined`)
    - [x] `icon` - `calcite-ui-icon` (`undefined`)
- [x] 2. Add new props: 
    - [x] `alignment` - boolean (`"start"` - default, `"center"`)
    - [x] `interactive` - boolean (`false`)
    - [x] `label` - string (`undefined`)
    - [x] `layout` - type (`"horizontal"` - default, `"vertical"`)
    - [x] `selection-appearance` - type  (`"icon"` - default, `"border"`)
    - [x] `selection-mode` - type (`"none"` - default, `"single"`, `"single-persist"`, `"multiple"`)
    - [x] `scale` - type (`"s"`, `"m"` - default, `"l"`)
    - [x] `selected`  - boolean (`false`) 
- [x] 4. Deprecate props:
    - [x] `embed` - boolean https://github.com/Esri/calcite-design-system/pull/8833
    - [x] `active` - boolean (no longer needed once selection modes are introduced)
- [x] 5. Add `min` and `max widths` to each `scale`
- [x] 6. Update `href` styling (Refer to the [Figma file](https://www.figma.com/file/8CiAVHkXIMTsI9hTSbotEz/Tile-Redesign-%5BEpic-6662%5D?type=design&node-id=720-2738&mode=design&t=ZAQtpcQRe2IVJM16-0) for a recording.
    - [x] No underline
    - [x] Blue border
    - [x] Blue icon
    - [x] Header on hover
   
![image](https://github.com/Esri/calcite-design-system/assets/5023024/b436a018-4ad3-470f-ac23-5ca64aec3a61)

- [x] 7. Replace `calcite-checkbox` with an icon https://github.com/Esri/calcite-design-system/issues/8834
    - [x] Consult with team members if the component could be a form element
    - [x] Icons: `"circle"` and `"circle-f"`
    
![image](https://github.com/Esri/calcite-design-system/assets/5023024/64c2c684-938d-4b3c-a96f-53317632a4bb)
![image](https://github.com/Esri/calcite-design-system/assets/5023024/c47646f9-8d87-4304-b978-dee01cde7cf8)

- [x] 8. Update hover and focused states

![image](https://github.com/Esri/calcite-design-system/assets/5023024/0a4ad47f-4bc1-4373-a6ce-11228c2c2dfa)

- [x] 9. Refer to #2141 to determine if a button mode is needed to support an entire clickable `tile` - the effort `needs discussion` from development team members.   

- [x] 10. Create the new `tile-group` component: https://github.com/Esri/calcite-design-system/issues/8615
- [x] 11. Deprecate icon size change when no description is provided
<img width="190" alt="image" src="https://github.com/Esri/calcite-design-system/assets/29716057/1a3261ea-729a-48f5-81e4-da1a83eeef15">

### Phase II
**Once the above work is completed, the following issues could be mitigated in the same PR**:
- [x] 1. Deprecate the `"content-start"` and `"content-end"`slots and move add `"content-top"` and `"content-bottom"` slots: https://github.com/Esri/calcite-components/issues/3462

- [ ] 2. Check spacing when no `heading` or `description` are present: https://github.com/Esri/calcite-components/issues/4701

- [ ] 3. Deprecate the `tile-select-group` component

### Related Issues
- [x] https://github.com/Esri/calcite-design-system/issues/8351
- [x] https://github.com/Esri/calcite-components/issues/4759

### No longer related issues
- ~https://github.com/Esri/calcite-components/issues/6690~
- ~https://github.com/Esri/calcite-components/issues/6691~
- ~https://github.com/Esri/calcite-components/issues/5937~
- ~https://github.com/Esri/calcite-components/issues/7215~

**Comment by macandcheese** [comment]
Scope should include merging three current tile components into just two - ‘tile’ and ‘tile-group’ pattern.

**Comment by SkyeSeitz** [comment]
Final specs are provided [here](https://www.figma.com/file/8CiAVHkXIMTsI9hTSbotEz/Tile-Redesign-%5BEpic-6662%5D?type=design&node-id=720%3A2738&mode=design&t=cHdYtB28RzLsSc4d-1).

**Comment by DitwanP** [comment]
🍠 Verified on `main`
