### ISSUE TITLE
Epic: Responsive layout across components

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6670]
### Description
Responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria
- [ ] 1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
- [ ] 2. Components need to be designed for the following breakpoints:
    - [ ] Small (s), `476px`
    - [ ] Medium (m), `768px`
    - [ ] Large (l), `1152px`
    - [ ] Extra larger (xl), `1440px`
    
### Relevant Info
https://user-images.githubusercontent.com/5023024/228056274-a06cf3bd-c9be-4612-bf1a-d049a09ccf5e.mov

#### Some minor adjustments required
- [x] ~`action-menu` #6672~
- [x] `alert` #6673 `ready for dev`
  - [x] https://github.com/Esri/calcite-design-system/issues/7921
- [x] `combobox` #4326 `ready for dev`
- [x] ~`dropdown` #6675~
- [x] ~`flow` #6676~
- [x] `input` #6677
- [x] `date-picker` #6678 `ready for dev`
- [x] ~`input-number` #6679~
- [x] ~`input-text` #6680~
- [x] ~`input-time-picker` #6681~
- [x] `notice` #6779  `ready for dev`
- [x]  `pagination` #6687  `ready for dev`
  - [x] https://github.com/Esri/calcite-design-system/issues/7856 `ready for dev`
- [x] ~`segmented-control` https://github.com/Esri/calcite-components/issues/6688~
- [x] `tabs` https://github.com/Esri/calcite-components/issues/6689 `ready for dev`
- [x] `tile` https://github.com/Esri/calcite-components/issues/6690 `ready for dev`
- [x] ~`tile-select-group` https://github.com/Esri/calcite-components/issues/6691~ `ready for dev`

#### Not fit for mobile, refactor might be needed
- [x] `checkbox` https://github.com/Esri/calcite-components/issues/6692 `ready for dev`
- [x] ~`shell` https://github.com/Esri/calcite-components/issues/6693~
- [x] `stepper` https://github.com/Esri/calcite-components/issues/6694 `ready for dev`

**Comment by DitwanP** [comment]
🍰 Verified the final component (`tabs`) for this epic.
