### ISSUE TITLE
[Date Picker] Responsive layout

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#6678]
### Description

Mobile responsiveness across Calcite Design System, focused on web (traditionally desktop sized web browser), tablet, phone screen sizes, and large monitors.

### Acceptance Criteria

- [x] 1. Consider breaking changes for folks. Consultation should occur on both the design and development teams.
- [x] 2. Components need to be designed for the following breakpoints:
    - [x] Small (s), `476px`
    - [x] Medium (m), `768px`
    - [x] Large (l), `1152px`
    - [ ] Extra larger (xl), `1440px`

### Relevant Info

Part of epic https://github.com/Esri/calcite-components/issues/6670

### Which Component

`input-date-picker`

### Priority impact

p4 - not time sensitive

### Esri team

Calcite (design)

**Comment by manuelalcosta** [comment]
Just applied the change on the variants on the 3 scales on the default variant

**Comment by SkyeSeitz** [comment]
Two recordings demonstrating the proposed behavior change:

**BEFORE**
https://user-images.githubusercontent.com/29716057/230445031-26be2f0b-e5f4-4335-b104-8d2534be116c.mov
**AFTER**
https://user-images.githubusercontent.com/29716057/230445076-0c1a36bd-8f1e-412f-ac75-ca6fbeee95d8.mov

**Comment by SkyeSeitz** [comment]
Completed responsive design available [here](https://www.figma.com/file/zBGnAOEOxqKGocUjqiYbed/Responsive-Layout?node-id=8279%3A183723&t=H0cPsE1ZwYk0UsRU-1).

**Comment by jcfranco** [comment]
I have a PR ready, but it is not low risk, so this would be better suited for the November release. cc @geospatialem

**Comment by geospatialem** [comment]
Verified in `1.11.0-next.3`
