### ISSUE TITLE
Epic: Combobox Redesign

### ISSUE THREAD

**Issue by brittneytewks** [Esri/calcite-design-system#6720]
### Description

Group combobox-related enhancement issues for consideration in a larger redesign. Accompanying enhancement issues should be considered during the redesign.

**Issues**

- [x] - **Should be mitigated first with 4738** - https://github.com/Esri/calcite-components/issues/3074 `ready-for-dev`
- [x] - **Should be mitigated first with 3074** - https://github.com/Esri/calcite-components/issues/4738 `ready-for-dev`
- [x] - https://github.com/Esri/calcite-components/issues/6412 `ready-for-dev`
- [x] - https://github.com/Esri/calcite-components/issues/5226 `ready-for-dev`
- [x] - https://github.com/Esri/calcite-components/issues/4326 `ready-for-dev`
- [x] - https://github.com/Esri/calcite-components/issues/3695 `ready-for-dev`
- [ ] - https://github.com/Esri/calcite-components/issues/2311 `ready-for-dev`
- [x] - https://github.com/Esri/calcite-components/issues/6421 `ready-for-dev`
- [x] - #2162 `design-complete`

**Comment by geospatialem** [comment]
Assigned to May for design, and development is tentatively scheduled for September.

**Comment by macandcheese** [comment]
Might be worth considering this as part of Combobox effort: https://github.com/Esri/calcite-components/issues/4334

**Comment by JonnyDawe** [comment]
I wanted to add some thoughts to this combobox epic. I would like to see better support for customisation of client/server side search capabilities of the Calcite Combobox akin to what is possible in other UI libraries such as ReachUI. 

[client-side search](https://reach.tech/combobox/#:~:text=Custom%20Option%20Rendering-,Clientside%20Search,-This%20demo%20searches)

[server-side search](https://reach.tech/combobox/#:~:text=Clientside%20Search-,Server%20Side%20Search,-This%20is%20the)

This functionality is somewhat currently replicable with the current Calcite Combobox as shown in this [US City Search Demo](https://codesandbox.io/s/admiring-nash-cdmz5t?file=/src/App.js). 

Unfortunately the implementation is hindered by the following:
 -  #7212 
 -  #7174 
 -  The added logic conflicts with internal filtering - see console warnings "No data was passed to the filter function.
    The data argument should be an array of objects"
 -  Poor options for adding non-selectable items - e.g. "No Results Found".
 -  Poor Options for adding custom actions into the combox box menu. E.g. Use my current location button.

Ideally it would be great to be able to achieve functionality similar to the Esri Search Widget in the JSAPI.

**Comment by JonnyDawe** [comment]
In addition to above I wanted to add an example of a custom typeahead stencil widget that we have developed which ideally we would want to try and eventually switch out to be a calcite component: https://i.imgur.com/IiSfUv3.mp4

**Comment by ashetland** [comment]
@JonnyDawe @geospatialem @macandcheese Would it be helpful to have the above logged as a new issue(s)?

**Comment by geospatialem** [comment]
Most of the efforts above have been tackled, with the exception of #2311. We will track the efforts in the linked issue separately, but the overall epic above is being closed out with the majority of effort complete. 🎉
