### ISSUE TITLE
Epic: DatePicker Redesign

### ISSUE THREAD

**Issue by brittneytewks** [Esri/calcite-design-system#6721]
### Description

Group DatePicker-related `enhancement` + `design` issues for consideration in a larger redesign. Accompanying enhancement issues should be considered during the redesign.

**Issues**

- [x] https://github.com/Esri/calcite-components/issues/6678 `ready-for-dev`
- [x] https://github.com/Esri/calcite-components/issues/3455 `ready-for-dev`
- [x] ~https://github.com/Esri/calcite-components/issues/3428~
- [ ] https://github.com/Esri/calcite-components/issues/3918 `ready-for-dev`
- [x] https://github.com/Esri/calcite-design-system/issues/6321 `ready-for-dev`
- [x] https://github.com/Esri/calcite-design-system/issues/6410 `ready-for-dev`
- [x] https://github.com/Esri/calcite-design-system/issues/8555

**Comment by SkyeSeitz** [comment]
Design specs that include re-work relevant to https://github.com/Esri/calcite-components/issues/6714, https://github.com/Esri/calcite-components/issues/6678, https://github.com/Esri/calcite-components/issues/3455, and https://github.com/Esri/calcite-components/issues/3918 can be found [here](https://www.figma.com/file/eP9IJjZV95HVKRCbNmW6eX/Input-Date-Picker-%5B%233455%5D?type=design&node-id=509-98979).

**Comment by SkyeSeitz** [comment]
Updated description with `ready for dev` statuses.

**Comment by geospatialem** [comment]
Closing out the above epic with one remaining date picker issue, which will be tracked through the individual issue. 🎉
