### ISSUE TITLE
Epic: Updates to Color Picker

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7163]
### Description

The design phase for adding alpha channel support to Color Picker (issue #749) proposed additional improvements that were intended to be tackled after the initial alpha channel support was implemented. This issue is to document the remaining tasks to complete. cc: @fr

### Acceptance Criteria

- [x] https://github.com/Esri/calcite-design-system/issues/9412
- [ ] https://github.com/Esri/calcite-design-system/issues/9413 
    - Update the internal borders inside channels input to be border-3. 
- [x] https://github.com/Esri/calcite-design-system/issues/9415
- [ ] https://github.com/Esri/calcite-design-system/issues/9414

### Relevant Info

For full details, updated Figma file can be found [here](https://www.figma.com/design/3YZypHvasD8KT4Y6cmQRKy/Color-Picker-Enhancements?node-id=65-20373).
 
**Note: the square color field mockups below would need approval from teams, but may also be unnecessary it the color field could be made responsive to container size (#9415).**

Historical screenshots of first pass on design below. Updated mocks are available in the associated issues above. 
![image](https://github.com/Esri/calcite-components/assets/108549080/fc5e7012-3a2b-4ffd-b3f8-64ac58f7ae06)
![image](https://github.com/Esri/calcite-components/assets/108549080/fe17bd09-697f-4ad6-90b0-fce2ddac3217)
![image](https://github.com/Esri/calcite-components/assets/108549080/66210fdb-27a5-448e-b516-1aba0df8304e)
![image](https://github.com/Esri/calcite-components/assets/108549080/dd9f02a0-326c-491c-a84c-85a56873fb45)

### Which Component

Color Picker

### Priority impact

impact - p2 - want for an upcoming milestone

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
@macandcheese @SkyeSeitz The above comment has been updated to reflect the changes we discussed.

**Comment by ashetland** [comment]
Note, the square color field above should have the lowest priority. Will need feedback from teams as it may have adverse affects on layouts.

**Comment by macandcheese** [comment]
Maybe a way for users to customize height of color graph? The square ones end up being significantly “taller” than previously - perhaps height graph prop for S/M/L? I think using css vars not possible with the color graph.

**Comment by geospatialem** [comment]
Most of the efforts above have been tackled, with the exception of #9413 and #9414. We will track the efforts in the linked issuea separately, but the overall epic above is being closed out with the majority of effort complete. 🎉
