### ISSUE TITLE
input-time-zone enhancements

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-design-system#7430]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

The following would be great additions to the time-zone picking experience:

* [ ] add a way to display a preview of local time across time zone options (⚠️ postponed until there's a greater demand)
  ![time-zone-labels](https://user-images.githubusercontent.com/197440/238069360-18abd52d-a355-4813-bf50-9363d983f3fa.png)
* [ ] display more info per time zone and also allow users to search for a time zone regardless of being listed or not
  ![time-zone-labels](https://user-images.githubusercontent.com/197440/238069470-db99ec09-be6f-492b-8008-9c9d94fa3fb6.png)
  Users should also have a way to set the time zone option by specifying the IANA time zone (must match a value from `Intl.supportedValuesOf("timeZone")`).

cc @ashetland

### Acceptance Criteria

- [ ] A property to enable each of the options from the description.
- [ ] Explore one of the following from [Richie's comment](https://github.com/Esri/calcite-design-system/issues/7430#issuecomment-1681069819) for accommodating timestamps:
  - Have two components `calcite-input-time-zone-offset` and `calcite-input-iana-time-zone`
  - Have one component, `calcite-input-time-zone`, with two modes (e.g. `"offset"`, `"iana-time-zone"` or `"name"`)
  - Keep `calcite-input-time-zone` as-is, where Ian uses a `calcite-combobox` with items populated from `Intl.supportedValuesOf('timeZone')` and translated using [this](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/input-time-zone/assets/input-time-zone/t9n/messages.json).
- [ ] Provide Daylight Savings Support or using a reference date from `calcite-date-picker` per [Richie's comment below](https://github.com/Esri/calcite-design-system/issues/7430#issuecomment-1681099248)
  -   _See the suggestion from Richie in the [comment link](https://github.com/Esri/calcite-design-system/issues/7430#issuecomment-1681099248)_
- [ ] Support internationalized string: _See the suggestion from Richie in the [following comment](https://github.com/Esri/calcite-design-system/issues/7430#issuecomment-1681116301)_

### Relevant Info

Stems from https://github.com/Esri/calcite-design-system/issues/6590#issuecomment-1654552443

### Which Component

`calcite-input-time-zone`

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by richiecarmichael** [comment]
> add a way to display a preview of local time across time zone options...

Do you have a use case for showing local time per offset. To me this totally does not make sense.

> display more info per time zone and also allow users to search for a time zone...

Will all 400+ named IANA time zones be accessible? It is not clear what the design is from this screenshot.

**Comment by jcfranco** [comment]
> Do you have a use case for showing local time per offset. To me this totally does not make sense.

Not a specific use case at the moment, but an affordance to show current time a recurring theme in time zone picker design resources:

* https://www.linkedin.com/pulse/designers-guide-time-zone-selection-ux-vitaly-friedman
* https://www.nngroup.com/articles/time-zone-selectors/
* https://bootcamp.uxdesign.cc/the-ux-of-timezones-7476a9685238

> Will all 400+ named IANA time zones be accessible? It is not clear what the design is from this screenshot.

Great question. All IANA time zones provided by the `Intl` API will be supported. Worth noting that not all of them will be listed in an option's label, but should still be searchable.

**Comment by richiecarmichael** [comment]
> ...but an affordance to show current time a recurring theme in time zone picker design resources:

I don't want to be too argumentative. Actually, I do. :-)  Two of those links reference **Calendly**, a scheduling app. My guess is that the local time preview would be used when an administrator is sending out meeting invites to remote people. This is very app specific.

A common scenario in GIS data entry. If I am in Redlands entering information about an electrical pole that was installed in New York a few moments ago.
1. I enter the date: "8/8/2023",
2. I enter the time: "5:00 PM",
3. I changes time zone from "GMT-7" (default) to "GMT-4" since "5:00pm" is in NY time.

Based on the design above the user will see a drop down containing "(GMT-7) 5:00pm", "(GMT-6) 4:00pm", "(GMT-5) 3:00pm", "(GMT-4:) 2:00pm" etc.  If I pick "(GMT-4:) 2:00pm" should the time change from 5:00pm to 2:00pm?  I'm just a little concerned that this will confuse users as I am.

**Comment by jcfranco** [comment]
You do bring up totally valid points, so thanks for sharing.

> This is very app specific.

Agreed. The current time preview would be something developers would opt into and not enabled by default.

Worth noting that the main enhancement we want to address here is the time zone name listing and search. We can put revisit the local time preview for a later time if deemed to confusing.

**Comment by ashetland** [comment]
> We can put revisit the local time preview for a later time if deemed too confusing.

@jcfranco completely agree that if this really doesn't make sense for the typical GIS user's mental model we should shelve it until, and if, it gets requested in the future.

**Comment by ian13262** [comment]
@jcfranco noting a potential enhancement: in addition to getting the offset value with `calciteInputTimeZone.value`, what about adding a property to retrieve the representative IANA string for a specific time zone (something like `calciteInputTimeZone.ianaString`, where this string is `"Africa/Dakar"`, etc.)? 

This would be useful when standardizing stored time zones in Map Viewer since system/unknown time zones are already stored as strings, not numeric values. The JSAPI would then handle all these strings similarly when updating times in popups/tables/other places.

**Comment by richiecarmichael** [comment]
As discussed yesterday `calcite-input-time-zone` satisfies the requirements of #6590 by returning a UTC offset in minutes. The component, originally named `calcite-input-time-zone-offset-picker`, was intended to be used to edit timestamps. It was not intended to pick a named time zone. This conflation is unfortunate.

#### To resolve we could explore one the following options:
1. Have two components `calcite-input-time-zone-offset` and `calcite-input-iana-time-zone`.
2. Have one component, `calcite-input-time-zone`, with two modes (e.g. `"offset"`, `"iana-time-zone"` or `"name"`).
3. Keep `calcite-input-time-zone` as is. @ian13262 uses a `calcite-combobox` with items populated from `Intl.supportedValuesOf('timeZone')` and translated using [this](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/input-time-zone/assets/input-time-zone/t9n/messages.json).

**Comment by richiecarmichael** [comment]
### Enhancement Request - Add Daylight Savings Support

## Description
`calcite-input-time-zone` should honor daylight savings of a reference date or `calcite-date-picker` component.

## Justification/Use Case
- Bob is FedEx customer service representative based in Fiji
- Bob is scheduling a pickup of two deliveries, one tomorrow and other six months from now.
- For the first delivery Bob adds a timestamp with the following values:
  - date: `8/16/2023`
  - time: `9:00 AM`
  - offset: `GMT-5` (Bob picks the item "(GMT-5) New York, Panama, Port au Prince"
- For the second delivery Bob adds a timestamp with the following values:
  - date: `4/16/2024`
  - time: `9:00 AM`
  - For offset Bob is confused. He sees "(GMT-5) New York, Panama, Port au Prince" in the dropdown but is certain that New York's offset in summer is `GMT-4`.

If Bob was accidently picked `GMT-5` for the second delivery this would actually arrive one hour earlier than expected.

## Suggestion
Add a property that references an input date picker.
```html
<body dir="rtl">
   <calcite-input-date-picker id="my-date-picker"/>
    <calcite-input-time-zone id="my-time-zone-offset" referenceDate="my-date-picker"/>
</body>
```
Specifically change [this](https://github.com/Esri/calcite-design-system/blob/43366358de11b50e306482061d53d85b3a42e129/packages/calcite-components/src/components/input-time-zone/utils.ts#L5-L8) code to:
```ts
export function getUserTimeZoneOffset(localDate: Date /* Get offset relative to parsed date */): number {
  //const localDate = new Date();
  return localDate.getTimezoneOffset() * -1;
}
```

**Comment by richiecarmichael** [comment]
### Enhancement Request - Internationalize "GMT-x"

The uniform "GMT" formatting [here](https://github.com/Esri/calcite-design-system/blob/43366358de11b50e306482061d53d85b3a42e129/packages/calcite-components/src/components/input-time-zone/utils.ts#L29-L31) can be replaced with the following that returns an internationalized string.

```js
function getTimeZoneShortOffset(date, timeZone, locale = "en-US") {
  const dateTimeFormat = new Intl.DateTimeFormat(locale, {
    timeZone,
    timeZoneName: "shortOffset"
  });
  const parts = dateTimeFormat.formatToParts(date);
  const { value } = parts.find(({ type }) => type === "timeZoneName");
  return value;
}
console.log(getTimeZoneShortOffset(new Date, "Pacific/Auckland", "en-US")); // "GMT+12"
console.log(getTimeZoneShortOffset(new Date, "Pacific/Auckland", "fr"));    // "UTC+12"
console.log(getTimeZoneShortOffset(new Date, "Pacific/Auckland", "ar"));    // "غرينتش+12"
```

// @ubatsukh

**Comment by jcfranco** [comment]
> #### To resolve we could explore one the following options:
1. Have two components `calcite-input-time-zone-offset` and `calcite-input-iana-time-zone`.
2. Have one component, `calcite-input-time-zone`, with two modes (e.g. `"offset"`, `"iana-time-zone"` or `"name"`).
3. Keep `calcite-input-time-zone` as is. @ian13262 uses a `calcite-combobox` with items populated from `Intl.supportedValuesOf('timeZone')` and translated using [this](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/input-time-zone/assets/input-time-zone/t9n/messages.json).

Apologies for the belated reply. We'll be proceeding w/ option 2 due to the following:

* There isn't a significant difference between name and offset modes UX/UI-wise to warrant separate components
* The component was intentionally named as it is to allow for additional modes
* Most usage would fall under one of either modes. In the event of needing both, the same component can be used w/ minimal configuration.

**Comment by geospatialem** [comment]
Verified in `main` with the `mode` property values of `"offset"` and `"name"`. Also tested `"offset"` with `referenceDate`.
