### ISSUE TITLE
[ArcGIS Online] [META] I18N-FCN-AR [FF/Safari]: Date is cleared after selecting a date and clicking on a blank area on Metadata page.

### ISSUE THREAD

**Issue by Olga8614** [Esri/calcite-design-system#7529]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

Date is cleared after selecting a date and clicking on a blank area on Metadata page.
Please refer the attachment "data_cant_be_selected.gif" for details.

### Expected Behavior

Date should not be cleared after selecting a date and clicking on a blank area on Metadata page.

### Reproduction Sample

- https://codepen.io/rpanichakit/pen/OJrLMRX?editors=100

- https://github.com/ArcGIS/I18N-BYS-TestCases/issues/11650

### Reproduction Steps

Codepen Steps:
1. Open the [Codepen](https://codepen.io/rpanichakit/pen/OJrLMRX?editors=100) in Firefox
2. Click calendar icon and select a date.
3. Click other blank area.
4. Observe.

DevExt Steps:
1. Prepare a clean AR FF browser.
3. Launch URL https://devext.arcgis.com and sign in with valid account.
4. Go to My content page and open item details page of a feature layer.
5. Click Metadata button.
6. Click "All metadata" tab, expand Metadata Info->Metadata Details.
7. Scroll to Metadata Data section.
8. Click calendar icon and select a date.
9. Click other blank area.
10. Observe.

### Reproduction Version

1.5.1

### Relevant Info

Additional Information:
1. This behavior also occurs with all other date fields.
2. This behavior also occurs with Safari (16.6) browser.
3. This behavior does not occur with Edge Chromium (115.0.1901.200)/Chrome (115.0.5790.171) browsers.
4. This behavior does not occur on AGOL 2023.r02 production site.

Configuration:
1. Build: AGOL 2023.r03 devext site
2. OS: AR Win10 64bit
3. Browser: Firefox (116.0.2)
4. Found by date: 8/11/2023

Build Number : 8/11/2023

### Regression?

N/A

### Priority impact

p3 - want for upcoming milestone

### Impact

N/A

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

ArcGIS Online

**Comment by Olga8614** [comment]
https://github.com/ArcGIS/I18N-BYS-Bugs/issues/16589

**Comment by Olga8614** [comment]
QV-B-Medium,CR-BY-Beyondsoft_I18N,QV-A-Bug,QV-C-I18N,QV-S-DevAssigned,QV-P-Firefox,QV-C-Many

**Comment by Olga8614** [comment]
Sample codepen: https://codepen.io/rpanichakit/pen/OJrLMRX?editors=100

**Comment by Olga8614** [comment]
![20935_data_cant_be_selected](https://github.com/Esri/calcite-design-system/assets/29614798/75f36be7-343f-45e7-8fb8-201b8fd7d96c)

**Comment by jcfranco** [comment]
@Olga8614 Could you provide more info on this issue? I can't repro with the codepen above.

**Comment by Olga8614** [comment]
@jcfranco can you please try the original issue description steps, at devext.arcgis.com? I don't have Safari browser handy today, sorry. Can try to get it tomorrow if needed.

**Comment by jcfranco** [comment]
@Olga8614 Ah, my bad. I missed the Safari/FF part. I see the issue now.

I'll update the description and add corresponding labels, but for next time, could you use the `bug` template when submitting a bug report? Otherwise, it might get missed by our filtering when we're doing triaging. Thanks!

**Comment by geospatialem** [comment]
Verified in `main` with FF on Windows.

![verify-7529](https://github.com/Esri/calcite-design-system/assets/5023024/0bf9aa88-fe32-4891-8d0f-e5a00ad47360)

**Comment by Olga8614** [comment]
@geospatialem 
We verified this defect on ArcGIS Online 2023.r03 devext site (9/8/2023) in AR language with FF (117.0)/Safari (16.6) browsers. Date is cleared after selecting a date and clicking on a blank area on Metadata page. It's the same behavior as the defect. So this defect is not fixed. Thanks!

**Comment by geospatialem** [comment]
> @geospatialem We verified this defect on ArcGIS Online 2023.r03 devext site (9/8/2023) in AR language with FF (117.0)/Safari (16.6) browsers. Date is cleared after selecting a date and clicking on a blank area on Metadata page. It's the same behavior as the defect. So this defect is not fixed. Thanks!

Was also able to duplicate on devext when the language is set to `"ar"`, but not with the [codepen sample](https://codepen.io/geospatialem/pen/GRPmoYV) with `1.8.0`. Sent a follow-up DM to Olga to investigate further.
