### ISSUE TITLE
[Epic] Consistent heading & description type and spacing for 5.0

### ISSUE THREAD

**Issue by SkyeSeitz** [Esri/calcite-design-system#7623]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

A decent handful of components contain a title & description pairing that could share a consistent type and gap treatment. 

### Acceptance Criteria
See [Figma file](https://www.figma.com/file/uONBOGXATHbZbh5APnSS94/Consistent-Title-%26-Description-treatments?type=design&node-id=1094%3A13614&mode=design&t=c8vutTGMSkF69MiS-1) for audit and specs.
cc @ashetland @macandcheese 

![image](https://github.com/user-attachments/assets/471e716c-e134-4424-8aef-6680d04f694e)

### Which Component
- [ ] Accordion Item #12306 
- [ ] Alert #11597 
- [ ] Block #12305 
- [ ] Card #12304 
- [x] Combobox Item #3695, #9881 
- [x] List Item #7100 
- [ ] Notice #10477
- [x] Panel & Flow Item #9862 
- [ ] Stepper Item #10720 
- [ ] Tile #10779 

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**monday.com sync:** #9365211383

**Comment by sagewall** [comment]
The ArcGIS Maps SDK for JavaScript LayerList is being refactored to use the calcite-list component and we've received some feedback that the font size is too small. Hoping this issue might resolve that.  Is there any way to get this prioritized?

**Comment by SkyeSeitz** [comment]
> The ArcGIS Maps SDK for JavaScript LayerList is being refactored to use the calcite-list component and we've received some feedback that the font size is too small. Hoping this issue might resolve that. Is there any way to get this prioritized?

Thanks, @sagewall - Agreed. This issue would look at bringing List Item text in line with the type size of the other similar components included in this audit. Prioritized for Feb 👍🏽

**Comment by geospatialem** [comment]
All the above linked issues have been installed and are ready for evaluation for a comprehensive look with verification. Thanks, @aPreciado88! 🤜🏻🤛🏻

**Comment by DintaMel** [comment]
I reverified all of the related issues. using version 5.0.0-next.80. I'm waiting to hear back on the shadow token for Notice in issue #10477. See [comment in 10477](https://github.com/Esri/calcite-design-system/issues/10477#issuecomment-3807511958).

**Comment by DintaMel** [comment]
I created issue #13790 to add a shadow token for Notice. Closing this issue since all spacing around heading and description is completed.
