### ISSUE TITLE
Epic: Support cancellable events across components

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7679]
**monday.com sync:** #18048704904

### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Audit and identify components where events should be cancellable for consistency across the design system.

- [ ] https://github.com/Esri/calcite-design-system/issues/3973 

Blocked issues: https://github.com/Esri/calcite-design-system/issues/3973

### Acceptance Criteria

Support cancellable events, such as `segmented-control`'s `calciteSegmentedControlChange` event, where events can be cancelled similar to the JS code depicted in https://codepen.io/geospatialem/pen/mdaOMPy.

### Which Component

All components (audit/identify)

### Example Use Case

https://codepen.io/geospatialem/pen/mdaOMP

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (dev)

**Comment by geospatialem** [comment]
Spike to audit the next steps of what is needed across the components. The audit results should be reflected in the above summary once completed.

**Comment by geospatialem** [comment]
The above should be audited by a PE once assigned to a future milestone.

**Comment by geospatialem** [comment]
During an internal meeting on March 31, 2026 the team discussed some approaches for event cancellation across components, and aim to explore use cases from internal teams to work through next steps for the next `spike` effort. 🏈 
 
Additional next steps include the following:
- We should explore use cases from teams, in particular the JS team, across event cancellation, in particular around custom vs. native events. cc @DitwanP 
- We should explore future guidance on approaches
    - Input change event, which restores text
    - Emitting on the host, which makes cancellation unsupported across some components
- Should we explore property support for more advanced use cases or complex functions with a callback
- Once direction is confirmed, we should coordinate with the Monday morning meeting with the SDK team to discuss next steps across the WebGIS SDK.
