### ISSUE TITLE
Epic: Audit and Update active states across components

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7717]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Conduct a design audit across all components to determine active and selected states, in particular for font weights.

### Acceptance Criteria

Consistent increases of font weights when components are selected or active across the design system.

### Relevant Info

- Surfaced in [this Community post](https://community.esri.com/t5/calcite-design-system-questions/target-active-selector-in-calcite-navigation/m-p/1326963#M497) WRT `menu-item`
- Previous internal discussions with `action` and `list`

### Which Component

All components

### Example Use Case

https://codepen.io/geospatialem/pen/NWepPxq

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by macandcheese** [comment]
Does this refer to active as as in css :active / pressed, or [active] as in the active property?

**Comment by macandcheese** [comment]
These component-level adjustments should be available as a result of design token effort. For example `--calcite-menu-item-press-text-color`, `--calcite-menu-item-press-background-color` (as an example, not sure final nomenclature).

**Comment by brittneytewks** [comment]
This will be resolved with Design Tokens
