### ISSUE TITLE
Epic: audit and consider visual updates to hover state styling across Calcite

### ISSUE THREAD

**Issue by ashetland** [Esri/calcite-design-system#7733]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Reevaluate Calcite hover state strategy for consistency and visual improvement. Take into consideration behaviors of slotted components.

### Acceptance Criteria

Improved hover states.

### Relevant Info

- [ ] #6930 
- [ ] #6245

_No response_

### Which Component

System-wide audit.

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react

### Esri team

Calcite (design)

**Comment by ashetland** [comment]
cc @SkyeSeitz @macandcheese Logged this for tracking purposes. We can update this as needed.

**Comment by ashetland** [comment]
This effort should also include ensuring consistency between hover and focus state styling.

**Comment by geospatialem** [comment]
Closing in favor of the interactive states of https://github.com/Esri/calcite-design-system/issues/9299
