### ISSUE TITLE
Epic: Accessibility (2024)

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#7851]
## Background
This epic organizes accessibility-related issues that surfaced from the 2022 accessibility audit with severities of 5-7. Higher priority issues will be or have been mitigated in the https://github.com/Esri/calcite-design-system/issues/4599 epic in 2023.

## Plan of action
With lower severities priorities will be investigated based on feedback from users, other Esri teams, and internal R&D from Calcite team members with the goal to address as many as possible in 2024.

Below names are associated with the verification of the issues.

## 2022 Audit (Severities 5-7)
- [ ] #7775 (Adam)
- [x] #7822 (Kitty)
- [x] #7776 (Adam)
- [x] #7777 (Adam)
- [x] #7778 (Adam)
- [x] #7779 (Adam)
- [x] #7780
- [x] #7781
- [x] #7782 (Franco)
- [x] #7783 (Franco)
- [x] #7784 (Franco)
- [x] #7785 (Franco)
- [x] #7786 (Franco)
- [x] #7787 (Kitty)
- [x] #7788 (Kitty)
- [x] #7789 (Kitty)
- [x] #7790 (Kitty)
- [x] #7791 (Kitty)
- [x] #7792 (Matt)
- [x] #7793 (Matt)
- [x] #7794 (Matt)
- [x] #7795 (Matt)
- [x] #7796 (Matt)
- [x] #7797 (Kitty)
- [ ] #7798 (Kitty)
- [x] #7799 (Kitty)
- [x] #7800 (Kitty)
- [x] #7801 (Kitty)
- [x] #7802
- [x] #7803
- [x] #7804 (Dec triage - Adam)
- [x] #7805
- [x] #7806 (Dec triage - Adam)
- [x] #7807
- [x] #7808 (Dec triage - Matt)
- [x] #7809
- [x] #7810
- [x] #7811
- [x] #7812
- [x] #7813
- [x] #7814
- [x] #7815
- [x] #7816
- [x] #7817
- [x] #7818
- [x] #7819
- [x] #7820
- [x] #7821
- [x] #7823
- [x] #7824
- [x] #7825
- [x] #7826
- [x] #7827
- [x] #7828 (Dec  triage - Matt)
- [x] #7829
- [x] #7830
- [x] #7831
- [x] #7832
- [x] #7833
- [x] #7834
- [x] #7835
- [x] #7836
- [ ] #7837 (Kitty)
- [x] #7838
- [x] #7839  (Kitty)
- [x] #7840
- [x] #7841
- [x] #7842
- [x] #7843
- [x] #7844
- [x] #7845
- [x] #7846  (Dec triage - Franco)
- [x] #7847  (Dec triage - Franco)
- [x] #7848
- [x] #7849
- [x] #7850

**Comment by geospatialem** [comment]
Most of the efforts above have been tackled, with the exception of #7775, #7798, and #7837. We will track the efforts in the linked issues separately, but the overall epic above is being closed out with the majority of effort complete. 🎉
