### ISSUE TITLE
Epic: Refactor/restructure sorting across components

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#8338]
### Description

Restructure/refactor the sorting component to support components across the design system, similar to the structure currently setup on `block`, where the parent supports the child component sorting.

Additional considerations include:
- keyboard support
- AT and keyboard support, in particular for Windows AT, JAWS and NVDA

### Proposed Advantages

Consistent approaches across components, such as:
1. A consistent story/implementation across components
2. Setting sorting on the parent component
3. Wiring up keyboard functionality consistently across the design system for keyboard and AT users

### Which Component

- `block`
- `list`
- `tree` - lower priority/future (?)
- `chip-group` - lower priority/future (?)

### Relevant Info

Came up as part of a discussion from #7445 via https://github.com/Esri/calcite-design-system/issues/7445#issuecomment-1688961553

Related: https://github.com/Esri/calcite-design-system/issues/7426

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by geospatialem** [comment]
Research spike to determine next steps for sorting across the design system. Some considerations:
- Do we want to provide a sorting utility?
- Should we consider sorting on the `block` component? We have previously had some support on the capability for teams

**Comment by driskull** [comment]
> Do we want to provide a sorting utility?

I think we decided against this. Our approach is to enable sorting on components that we want to allow sorting.

> Should we consider sorting on the block component? We have previously had some support on the capability for teams

We added a block group component to handle this.

@geospatialem @brittneytewks Is there any further work on this issue? I think tree/chip-group could have their own issue and discussion if necessary.

**Comment by geospatialem** [comment]
> > Do we want to provide a sorting utility?
> 
> I think we decided against this. Our approach is to enable sorting on components that we want to allow sorting.
> 
> > Should we consider sorting on the block component? We have previously had some support on the capability for teams
> 
> We added a block group component to handle this.
> 
> [@geospatialem](https://github.com/geospatialem) [@brittneytewks](https://github.com/brittneytewks) Is there any further work on this issue? I think tree/chip-group could have their own issue and discussion if necessary.

Closing in favor of two new issues to track sorting, including:
- Chip Group/Chip: https://github.com/Esri/calcite-design-system/issues/11962
- Tree/Tree Item: https://github.com/Esri/calcite-design-system/issues/11963

As Matt mentions above the Block Group/Block implementation is complete, and we are moving away from a sorting utility.
