### ISSUE TITLE
Research: determine the potential impact of applying REM-based tokens to all components

### ISSUE THREAD

**Issue by alisonailea** [Esri/calcite-design-system#8856]
**monday.com sync:** #18048397906

### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

REM-based tokens provide levels of flexibility that may be preferable for users. However, due to the base value being tied to the global `font-size` CSS prop, this will likely have ripple effects across components. Thorough testing needed.

#### Dependant on:
- [x] Add semantic space (rem) tokens: #10012
- [x] Add semantic size (rem) tokens: #10014
- [x] Add semantic font-size-relative (rem) tokens: #13037
- [x] Add REM-based design tokens: #10051
- [ ] Update tailwind-preset to reference semantic tokens: #10052

### Acceptance Criteria

Test the impact using REM-based variables on specific elements within Calcite Components has:
- [ ] `size` tokens for height, width, inline-size, block-size, and scale
- [ ] `space` tokens for padding, margin, gap, etc.
- [ ] `font-size-relative` and `font-line-height` tokens for heading text and body text

### Relevant Info

#13657: Research: if a custom font-size variable could modify text elements (specifically) across components

Tailwind has previously covered this with a selection of "applied" tailwind classes. In many components, these have been replaced with direct "space" or "line-height" properties. So both will need to be searched for.

Style Dictionary has built-in transforms like `size/pxToRem` that could help with variable conversions for testing purposes and potentially for any large-scale token value updates ([details](https://styledictionary.com/reference/hooks/transforms/predefined/#sizepxtorem))

### Which Component

N/A

### Example Use Case

```
.scale-m {
  @apply text-n1h;
  padding: var(--calcite-space-sm);
  max-width: var(--calcite-size-2xl);
}
```

### Priority impact

p3 - want for upcoming milestone

### Calcite package

- [X] @esri/calcite-components
- [X] @esri/calcite-design-tokens

### Esri team

Calcite (dev)

### Original description

>### Description
>
>#### Pre-November
>- [x] Review space and size tokens from design. Note changes to values in existing tokens
>- ~~[ ] create token transformer script to convert semantic space, size, and font-size tokens to REMs. (#10051)~~
>
>#### November release
>
>##### Calcite Design Tokens
>- [x] add and update tokens to semantic design tokens package.
>    - [x] Size (#10014)
>    - [x] Space (#10012)
>
>##### Calcite Components
>- [ ] update calcite-preset to use calcite-design-tokens for spacing, sizing, font-size, and line-height (#10052)
>- [ ] update components to use newly tokens where applicable. Spacing, Sizing, and Font-size.
>
>### Acceptance Criteria
>
>- [ ] Semantic tier spacing, sizing, and font-size variables build to CSS with REM values with a 16px base
>- [ ] Calcite Components use Calcite Design Tokens for all spacing, sizing, and font-size references. 
>- [ ] values for height, width, inline-size, block-size, and scale should use "sizing" tokens
>- [ ] values for padding, margin, gap, etc should use "spacing" tokens
>- [ ] line-height and font-size should use "font-size" tokens

**Comment by alisonailea** [comment]
This should be as easy as adding https://amzn.github.io/style-dictionary/#/transforms?id=sizepxtorem to the Design Token's build

**Comment by geospatialem** [comment]
Adding the breaking change label as this _could_ have some repercussions for teams, although the intent is for visual changes on the change (e.g., font size changes across components).

**Comment by matgalla** [comment]
This issue has been re-scoped towards research to ensure we have the opportunity assess all the possible ripple effects that a full-scale switch from `px` to `rem`-based tokens would have. The primary acceptance criteria has been updated to reflect these action items.

We're also planning to meet with the Maps SDK team mid-March to discuss the `font-size` variables @geospatialem mentioned above. Typography cleanup work (#11902) planned for our March milestone will also inform this effort.

**Comment by matgalla** [comment]
## Spike complete

**Topic:**
`font-size` sliders in apps and icons not scaling with REMs

**Contributors:**
Members from Web GIS SDK, ExB, and Graphics and Illustration teams

**Conclusions:**
- Icons do scale with browser-level zoom settings and shouldn't be an a11y concern
- No current action items with regard to fixed icon sizes
- Existing issues are primarily the result of `space` tokens being unexpectedly REM-based

**Action Items:**
- Research pros/cons of REM-based spacing
- Confirm the impact of converting existing semantic `space` tokens to fixed pixels instead of REMs

**Comment by matgalla** [comment]
Paused until higher-priority issues are resolved (likely until September)
