### ISSUE TITLE
date-picker: focus is missing when using arrow/page keys to switch between months

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-design-system#9062]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

When using arrowDown/arrowUp ( OR pageUp/pageDown) to change the activeDate and if the activeDate falls in next/previous month the focus is missing. 

### Expected Behavior

- arrowDown/arrowUp should focus the activeDate if it falls in next or previous month.
- pageUp/pageDown should focus the activeDate if it falls in next or previous month.

### Reproduction Sample

https://codepen.io/anvesh-mekala/pen/jORZWxp

### Reproduction Steps

1. Open Codepen sample
2. Tab into the date-picker
3. Once the activeDate is focused , use arrowDown or arrowUp to navigate to different month.
4. Repeat the above step and use pageDown/pageUp keys to navigate different month.
5. Observe once the month changes , focus is missing on activeDate.

### Reproduction Version

2.7.1

### Priority impact

p2 - want for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by DitwanP** [comment]
🍡 Verified on `2.8.0-next.0`
