### ISSUE TITLE
[Tokens Epic] Restore Input corner-radius behavior

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-design-system#9083]
### Description

In #7180 (in progress) - some of the Input corner-radius behavior was lost. It was working at the time of introduction into the epic: https://github.com/Esri/calcite-design-system/pull/8767#issuecomment-1956019031

### Proposed Advantages

The component should behave as it did when introduced.

### Which Component

Input (and any Input related components)

### Relevant Info

It was functioning as-expected when initially merged in to #7180, so it was likely a merge conflict or other epic-related change.

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by macandcheese** [comment]
Addressed by https://github.com/Esri/calcite-design-system/pull/10820
