### ISSUE TITLE
Epic: Interactive states across the design system for hover, press, and focus

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9299]
### Description
Audit and update interactive states across the design system WRT the following states:
- hover
- press
- focus

cc @ashetland @SkyeSeitz 

### Proposed advantages
- Consistent and expected states
- More a11y support and benefits to our users

### Phases and components

[Figma file](https://www.figma.com/design/c6v9o8y5KgztitlvDudaQy/Interactive-state-audit-%26-improvements?node-id=1-2&t=J8pxiqWOzqfYHpD3-0)

#### Phase I: January 2025
- [x] `tile`
- [x] `pagination` https://github.com/Esri/calcite-design-system/issues/9991
- [x] `stepper-item` https://github.com/Esri/calcite-design-system/issues/10000
- [x] `menu` https://github.com/Esri/calcite-design-system/issues/10001

#### Phase II: February 2025
- [x] `navigation-logo` + `navigation-user` https://github.com/Esri/calcite-design-system/issues/10002
- [x] `tabs` https://github.com/Esri/calcite-design-system/issues/10003

#### Phase III: March 2025
- [x] `button` https://github.com/Esri/calcite-design-system/issues/9246
- [x] `chip` https://github.com/Esri/calcite-design-system/issues/10005
- [x] `combobox-item` #6245 
- [x] `combobox-item` #11646 
- [x] `action` https://github.com/Esri/calcite-design-system/issues/10007
- [x] `segmented-control` https://github.com/Esri/calcite-design-system/issues/10013
- [x] `rating` https://github.com/Esri/calcite-design-system/issues/10015

#### Phase IV: May 2025
- [x] `button` follow ups https://github.com/Esri/calcite-design-system/issues/11576
- [x] `fab` https://github.com/Esri/calcite-design-system/issues/10004
- [x] `accordion` https://github.com/Esri/calcite-design-system/issues/10016
- [x] `block` https://github.com/Esri/calcite-design-system/issues/10017
- [x] `list` https://github.com/Esri/calcite-design-system/issues/10018
- [x] `dropdown` https://github.com/Esri/calcite-design-system/issues/10019

#### Phase V: July 2025
- [x] `checkbox` https://github.com/Esri/calcite-design-system/issues/10020
- [x] `radio-button` https://github.com/Esri/calcite-design-system/issues/10021

#### Future / Ignored for now
- [x] `slider`
- [ ] `tree` https://github.com/Esri/calcite-design-system/issues/6930
- [x] `switch`

#### Follow-up changes / fixes
- [x] `chip` https://github.com/Esri/calcite-design-system/issues/12286

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components
