### ISSUE TITLE
Remove deprecations for `action-group`, `color-picker`, `shell-panel`, `table`, `checkbox` and `radio-button`

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-design-system#9713]
### Description

- [x] Remove Action Group's `layout` property #10792 
- [x] Remove Color Picker's `hideChannels`, `hideHex` and `hideSaved` properties #10790 
- [x] Remove Shell Panel `detachedHeightScale` + `detached` properties and `--calcite-shell-panel-detached-max-height` CSS property #10794
- [x] Removes Table's `zebra` property #10795
- [x] Remove Checkbox's `guid` property #10797
- [x] Remove Radio Button's `guid` property #10799

### Proposed Advantages

Removes deprecations from `1.4.0` (May 2023).

### Which Component

- `action-group`
- `color-picker`
- `shell-panel`
- `table`
- `checkbox`
- `radio-button`

### Relevant Info

Stems from the following closed issues, where deprecations took place.
- #6390 
- #749
- #6919 
- #7906

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-angular
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

**Comment by DitwanP** [comment]
Verified locally on `dev`
